#!/bin/bash -e
tar xf linux-5.10.17.tar.xz
pushd linux-5.10.17
make mrproper
make headers
find usr/include -name '.*' -delete
rm usr/include/Makefile
cp -rv usr/include $LFS/usr
popd
rm -rf linux-5.10.17
touch /tmp/yes
