#!/bin/bash -e
tar xf glibc-2.33.tar.xz
pushd glibc-2.33
ln -sfv ../lib/ld-linux-x86-64.so.2 $LFS/lib64
ln -sfv ../lib/ld-linux-x86-64.so.2 $LFS/lib64/ld-lsb-x86-64.so.3
patch -Np1 -i ../glibc-2.33-fhs-1.patch
mkdir build
pushd build
../configure                             \
      --prefix=/usr                      \
      --host=$LFS_TGT                    \
      --build=$(../scripts/config.guess) \
      --enable-kernel=3.2                \
      --with-headers=$LFS/usr/include    \
      libc_cv_slibdir=/lib
make
make DESTDIR=$LFS install
echo 'int main(){}' > dummy.c
$LFS_TGT-gcc dummy.c
if [ "$(readelf -l a.out | grep '/ld-linux')" = "" ]
then
	cat invalidfile
fi
popd
popd
$LFS/tools/libexec/gcc/$LFS_TGT/10.2.0/install-tools/mkheaders
rm -rf glibc-2.33
touch /tmp/yes
