#!/bin/bash -e
tar xf file-5.39.tar.gz
pushd file-5.39
mkdir build
pushd build
../configure --disable-bzlib        \
               --disable-libseccomp \
               --disable-xzlib      \
               --disable-zlib
make
popd
./configure --prefix=/usr --host=$LFS_TGT --build=$(./config.guess)
make FILE_COMPILE=$(pwd)/build/src/file
make DESTDIR=$LFS install
popd
rm -rf file-5.39
touch /tmp/yes
