#!/bin/bash -e
tar xf findutils-4.8.0.tar.xz
pushd findutils-4.8.0
./configure --prefix=/usr   \
            --host=$LFS_TGT \
            --build=$(build-aux/config.guess)
make
make DESTDIR=$LFS install
mv -v $LFS/usr/bin/find $LFS/bin
sed -i 's|find:=${BINDIR}|find:=/bin|' $LFS/usr/bin/updatedb
popd
rm -rf findutils-4.8.0
touch /tmp/yes
