#!/bin/bash -e
tar xf grep-3.6.tar.xz
pushd grep-3.6
./configure --prefix=/usr   \
            --host=$LFS_TGT \
            --bindir=/bin
make
make DESTDIR=$LFS install
popd
rm -rf grep-3.6
touch /tmp/yes
