#!/bin/bash -e
tar xf make-4.3.tar.gz
pushd make-4.3
./configure --prefix=/usr   \
            --without-guile \
            --host=$LFS_TGT \
            --build=$(build-aux/config.guess)
make
make DESTDIR=$LFS install
popd
rm -rf make-4.3
touch /tmp/yes
