#!/bin/bash -e
tar xf sed-4.8.tar.xz
pushd sed-4.8
./configure --prefix=/usr   \
            --host=$LFS_TGT \
            --bindir=/bin
make
make DESTDIR=$LFS install
popd
rm -rf sed-4.8
touch /tmp/yes
