#!/bin/bash -e
tar xf tar-1.34.tar.xz
pushd tar-1.34
./configure --prefix=/usr                     \
            --host=$LFS_TGT                   \
            --build=$(build-aux/config.guess) \
            --bindir=/bin
make
make DESTDIR=$LFS install
popd
rm -rf tar-1.34
touch /tmp/yes
