#!/bin/bash

if [ "$INTERACTIVE" ]
then
	exec bash
	exit
fi
if ! [[ -d $LFS ]]
then
	echo "Installation target not mounted"
	exit
fi
if [ "$NOBUILD" != "yes" ]
then
mkdir -pv $LFS/{bin,etc,lib,sbin,usr,var,tools,lib64}
chown -v lfs $LFS/{usr,lib,var,etc,bin,sbin,tools,lib64,sources}
chown -v lfs /sources
sudo -u lfs /scripts/toolchain
if ! [[ -f /tmp/yes ]]
then
        echo "Toolchain build failed"
        exit
fi
rm /tmp/yes
chown -R root:root $LFS/{usr,lib,var,etc,bin,sbin,tools}
case $(uname -m) in
  x86_64) chown -R root:root $LFS/lib64 ;;
esac
mkdir -pv $LFS/{dev,proc,sys,run}
mknod -m 600 $LFS/dev/console c 5 1
mknod -m 666 $LFS/dev/null c 1 3
fi
mount -v --bind /dev $LFS/dev
mount -v --bind /dev/pts $LFS/dev/pts
mount -vt proc proc $LFS/proc
mount -vt sysfs sysfs $LFS/sys
mount -vt tmpfs tmpfs $LFS/run
if [ -h $LFS/dev/shm ]; then
  mkdir -pv $LFS/$(readlink $LFS/dev/shm)
fi
mkdir -pv $LFS/{sources,scripts}
mount --bind /sources $LFS/sources
mount --bind /scripts $LFS/scripts
if [ "$NOBUILD" != "yes" ]
then
install -m644 /sources/files/{passwd,group} $LFS/etc/

chroot "$LFS" /usr/bin/env -i   \
    HOME=/root                  \
    TERM="$TERM"                \
    MAKEFLAGS="$MAKEFLAGS"      \
    PS1='(lfs chroot) \u:\w\$ ' \
    PATH=/bin:/usr/bin:/sbin:/usr/sbin \
    /scripts/chroot-build
if [ -f $LFS/tmp/yes ]
then
	rm /tmp/yes
else
	echo "software build failed"
	exit
fi
fi
if ! [[ -f $LFS/etc/fstab ]]
then
	install -m644 /sources/files/fstab $LFS/etc/
	genfstab -U $LFS >> $LFS/etc/fstab
fi
GRUBTGT=$(genfstab $LFS | grep "\s/\s" | awk '{print $1}' | sed 's/[0-9]$//g')
echo "GRUBTGT before chroot: $GRUBTGT"
chroot "$LFS" /usr/bin/env -i          \
    HOME=/root TERM="$TERM"            \
    MAKEFLAGS="$MAKEFLAGS"             \
    GRUBTGT="$GRUBTGT" 		       \
    PS1='(lfs chroot) \u:\w\$ '        \
    PATH=/bin:/usr/bin:/sbin:/usr/sbin \
    /scripts/chroot-setup
