#!/bin/bash
tar xf Python-3.9.2.tar.xz
pushd Python-3.9.2
./configure --prefix=/usr   \
            --enable-shared \
            --without-ensurepip
make
make install
popd
rm -rf Python-3.9.2
touch /tmp/yes
