#!/bin/bash -e
tar xf zlib-1.2.11.tar.xz
pushd zlib-1.2.11
./configure --prefix=/usr
make
make install
mv -v /usr/lib/libz.so.* /lib
ln -sfv ../../lib/$(readlink /usr/lib/libz.so) /usr/lib/libz.so
rm -fv /usr/lib/libz.a
popd
rm -rf zlib-1.2.11
touch /tmp/yes
