#!/bin/bash -e
tar xf zstd-1.4.8.tar.gz
pushd zstd-1.4.8
make
make prefix=/usr install
rm -v /usr/lib/libzstd.a
mv -v /usr/lib/libzstd.so.* /lib
ln -sfv ../../lib/$(readlink /usr/lib/libzstd.so) /usr/lib/libzstd.so
popd
rm -rf zstd-1.4.8
touch /tmp/yes
