#!/bin/bash -e
tarball="bc-3.3.0.tar.xz"
dirname=$(echo $tarball | awk -F.tar '{print $1}')
tar xf $tarball
pushd $dirname
PREFIX=/usr CC=gcc ./configure.sh -G -O3
make
make install
popd
rm -rf $dirname
touch /tmp/yes
