#!/bin/bash
tarball="mpfr-4.1.0.tar.xz"
dirname=$(echo $tarball | awk -F.tar '{print $1}')
tar xf $tarball
pushd $dirname
./configure --prefix=/usr        \
            --disable-static     \
            --enable-thread-safe \
            --docdir=/usr/share/doc/mpfr-4.1.0
make
make html
make check
make install
make install-html
popd
rm -rf $dirname
touch /tmp/yes
