#!/bin/bash -e
tarball="mpc-1.2.1.tar.gz"
dirname=$(echo $tarball | awk -F.tar '{print $1}')
tar xf $tarball
pushd $dirname
./configure --prefix=/usr    \
            --disable-static \
            --docdir=/usr/share/doc/mpc-1.2.1
make
make html
make install
make install-html
popd
rm -rf $dirname
touch /tmp/yes
