#!/bin/bash -e
tarball="attr-2.4.48.tar.gz"
dirname=$(echo $tarball | awk -F.tar '{print $1}')
tar xf $tarball
pushd $dirname
./configure --prefix=/usr     \
            --bindir=/bin     \
            --disable-static  \
            --sysconfdir=/etc \
            --docdir=/usr/share/doc/attr-2.4.48
make
make install
mv -v /usr/lib/libattr.so.* /lib
ln -sfv ../../lib/$(readlink /usr/lib/libattr.so) /usr/lib/libattr.so
popd
rm -rf $dirname
touch /tmp/yes
