#!/bin/bash -e
tarball="bison-3.7.5.tar.xz"
dirname=$(echo $tarball | awk -F.tar '{print $1}')
tar xf $tarball
pushd $dirname
./configure --prefix=/usr --docdir=/usr/share/doc/bison-3.7.5
make
make install
popd
rm -rf $dirname
touch /tmp/yes
