#!/bin/bash -e
tarball="grep-3.6.tar.xz"
dirname=$(echo $tarball | awk -F.tar '{print $1}')
tar xf $tarball
pushd $dirname
./configure --prefix=/usr --bindir=/bin
make
make install
popd
rm -rf $dirname
touch /tmp/yes
