#!/bin/bash -e
tarball="gperf-3.1.tar.gz"
dirname=$(echo $tarball | awk -F.tar '{print $1}')
tar xf $tarball
pushd $dirname
./configure --prefix=/usr --docdir=/usr/share/doc/gperf-3.1
make
make install
popd
rm -rf $dirname
touch /tmp/yes
