#!/bin/bash -e
tarball="XML-Parser-2.46.tar.gz"
dirname=$(echo $tarball | awk -F.tar '{print $1}')
tar xf $tarball
pushd $dirname
perl Makefile.PL
make
make install
popd
rm -rf $dirname
touch /tmp/yes
