#!/bin/bash -e
tarball="libffi-3.3.tar.gz"
dirname=$(echo $tarball | awk -F.tar '{print $1}')
tar xf $tarball
pushd $dirname
./configure --prefix=/usr --disable-static --with-gcc-arch=native
make
make install
popd
rm -rf $dirname
touch /tmp/yes
