#!/bin/bash -e
tarball="gawk-5.1.0.tar.xz"
dirname=$(echo $tarball | awk -F.tar '{print $1}')
tar xf $tarball
pushd $dirname
sed -i 's/extras//' Makefile.in
./configure --prefix=/usr
make
make install
mkdir -v /usr/share/doc/gawk-5.1.0
cp    -v doc/{awkforai.txt,*.{eps,pdf,jpg}} /usr/share/doc/gawk-5.1.0
popd
rm -rf $dirname
touch /tmp/yes
