#!/bin/bash -e
tarball="libpipeline-1.5.3.tar.gz"
dirname=$(echo $tarball | awk -F.tar '{print $1}')
tar xf $tarball
pushd $dirname
./configure --prefix=/usr
make
make install
popd
rm -rf $dirname
touch /tmp/yes
