#!/bin/bash -e
tarball="patch-2.7.6.tar.xz"
dirname=$(echo $tarball | awk -F.tar '{print $1}')
tar xf $tarball
pushd $dirname
./configure --prefix=/usr
make
make install
popd
rm -rf $dirname
touch /tmp/yes
