#!/bin/bash -e
tarball="procps-ng-3.3.17.tar.xz"
dirname="procps-3.3.17"
tar xf $tarball
pushd $dirname
./configure --prefix=/usr                            \
            --exec-prefix=                           \
            --libdir=/usr/lib                        \
            --docdir=/usr/share/doc/procps-ng-3.3.17 \
            --disable-static                         \
            --disable-kill
make
make install
mv -v /usr/lib/libprocps.so.* /lib
ln -sfv ../../lib/$(readlink /usr/lib/libprocps.so) /usr/lib/libprocps.so
popd
rm -rf $dirname
touch /tmp/yes
