#!/bin/bash -e
tarball="sysklogd-1.5.1.tar.gz"
dirname=$(echo $tarball | awk -F.tar '{print $1}')
tar xf $tarball
pushd $dirname
sed -i '/Error loading kernel symbols/{n;n;d}' ksym_mod.c
sed -i 's/union wait/int/' syslogd.c
make
make BINDIR=/sbin install
install -m644 /sources/files/syslog.conf /etc/
popd
rm -rf $dirname
touch /tmp/yes
