#!/bin/bash -e
tarball="sysvinit-2.98.tar.xz"
dirname=$(echo $tarball | awk -F.tar '{print $1}')
tar xf $tarball
pushd $dirname
patch -Np1 -i ../sysvinit-2.98-consolidated-1.patch
make
make install
popd
rm -rf $dirname
touch /tmp/yes
